# Generated by Django 3.1.7 on 2021-04-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='employee_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('narration', models.CharField(max_length=200)),
                ('placename', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='media_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='media_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='request_public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('houseno_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='service_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('area_locality', models.CharField(max_length=50)),
                ('area_district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('houseno_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.login')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('houseno_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.login')),
            ],
        ),
        migrations.CreateModel(
            name='monthly_settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('MEDIAPROVIDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.media_provider')),
            ],
        ),
        migrations.AddField(
            model_name='media_provider',
            name='MEDIATYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.media_type'),
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_title', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('ADVERTISEMENTREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.advertisement_request')),
            ],
        ),
        migrations.CreateModel(
            name='maintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('maintance', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=50)),
                ('INSTALLATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.installation')),
                ('SERVICEAREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.service_area')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.staff')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='SERVICEAREA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.service_area'),
        ),
        migrations.AddField(
            model_name='installation',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.staff'),
        ),
        migrations.CreateModel(
            name='feedback_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.user')),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=50)),
                ('EMPLOYEEAREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.employee_area')),
            ],
        ),
        migrations.AddField(
            model_name='employee_area',
            name='SERVICEAREA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.service_area'),
        ),
        migrations.AddField(
            model_name='employee_area',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.staff'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=50)),
                ('reply', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.user')),
            ],
        ),
        migrations.CreateModel(
            name='charge_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=50)),
                ('profilename', models.CharField(max_length=50)),
                ('MEDIAPROVIDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.media_provider')),
                ('MEDIATYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.media_type')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement_request',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarna_advertisers.user'),
        ),
    ]
