# Generated by Django 3.1.7 on 2021-03-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarna_advertisers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media_provider',
            old_name='gender',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='media_provider',
            old_name='houseno_name',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='media_provider',
            name='dob',
        ),
    ]
